### ISSUE TITLE
Error Exporting Channel (path Parameter is null)

### ISSUE THREAD

**Issue by okok7711** [Tyrrrz/DiscordChatExporter#1179]
### Version

v2.42.6

### Flavor

CLI (Command-Line Interface)

### Platform

Docker

### Export format

JSON

### Steps to reproduce

This issue only exists in one DM channel, I can't share an invite to that.
I also can't reproduce it with any other channel.
What I did:
1. `docker pull tyrrrz/discordchatexporter:stable`
2. Find Channel of Deleted User and copy CHANNEL_ID, and copy my TOKEN
3. `docker run --rm -it -v $PWD:/out tyrrrz/discordchatexporter:stable export -t "<TOKEN>" -c <CHANNEL_ID> --media -f Json --filter "-from:<my_name>"`

### Details

- Expected Behaviour: Export Chat with media
- Observed Behaviour: `TargetInvocationException`
Stacktrace:
```
ERROR
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
    System.ArgumentNullException: Value cannot be null. (Parameter 'path')
      at System.ArgumentNullException.Throw(String paramName)
      at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
      at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
      at System.IO.Path.GetFullPath(String path)
      at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.set_OutputPath(String value) in /tmp/app/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:42
      at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
      at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  at CliFx.Schema.BindablePropertyDescriptor.SetValue(ICommand commandInstance, Object value) in /_/CliFx/Schema/BindablePropertyDescriptor.cs:19
  at CliFx.CommandBinder.BindMember(IMemberSchema memberSchema, ICommand commandInstance, IReadOnlyList`1 rawValues) in /_/CliFx/CommandBinder.cs:244
  at CliFx.CommandBinder.BindOptions(CommandInput commandInput, CommandSchema commandSchema, ICommand commandInstance) in /_/CliFx/CommandBinder.cs:346
  at CliFx.CommandBinder.Bind(CommandInput commandInput, CommandSchema commandSchema, ICommand commandInstance) in /_/CliFx/CommandBinder.cs:402
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in /_/CliFx/CliApplication.cs:162
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in /_/CliFx/CliApplication.cs:204
```
- Additional Information: As stated in the Reproduction section, I can't reproduce with any other channel except for this Deleted User's channel. Even for other Deleted Users it works fine, just for this singular user it doesn't. If there's anything I can give to help or try, I'll do that

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by okok7711** [comment]
This was probably caused due to a parser error so I should've used the ~ I apologise for creating the issue for that
