### ISSUE TITLE
Downloading PMs doesn't seem to work

### ISSUE THREAD

**Issue by MichaelBlume** [Tyrrrz/DiscordChatExporter#204]
```
docker run --rm -v ${PWD}:/app/out tyrrrz/discordchatexporter export -t [my token] -c [PM ID]
DiscordChatExporter.Core.Services.Exceptions.HttpErrorStatusCodeException: Error HTTP status code: NotFound - NOT FOUND
   at DiscordChatExporter.Core.Services.DataService.<>c__DisplayClass1_0.<<GetApiResponseAsync>b__2>d.MoveNext() in /src/DiscordChatExporter.Core.Services/DataService.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at Failsafe.Retry.ExecuteAsync[TReturn](Func`1 taskFunction)
   at Failsafe.Retry.ExecuteAsync[TReturn](Func`1 taskFunction)
   at DiscordChatExporter.Core.Services.DataService.GetApiResponseAsync(AuthToken token, String resource, String endpoint, String[] parameters) in /src/DiscordChatExporter.Core.Services/DataService.cs:line 31
   at DiscordChatExporter.Core.Services.DataService.GetChannelAsync(AuthToken token, String channelId) in /src/DiscordChatExporter.Core.Services/DataService.cs:line 87
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in /src/DiscordChatExporter.Cli/Commands/ExportChannelCommand.cs:line 22
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments)```

**Comment by RenanYudi** [comment]
[Are you copying the DM ID, not the User ID?](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-dm-channel-id)

**Comment by MichaelBlume** [comment]
Thank, you, no I wasn't
