### ISSUE TITLE
HTTP Not Found

### ISSUE THREAD

**Issue by dudeamax99** [Tyrrrz/DiscordChatExporter#233]
Getting this error after running discord chat exporter cli
`DiscordChatExporter.Core.Services.Exceptions.HttpErrorStatusCodeException: Error HTTP status code: NotFound - NOT FOUND
   at DiscordChatExporter.Core.Services.DataService.<>c__DisplayClass1_0.<<GetApiResponseAsync>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Failsafe.Retry.<ExecuteAsync>d__8``1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Failsafe.Retry.<ExecuteAsync>d__8``1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DiscordChatExporter.Core.Services.DataService.<GetApiResponseAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DiscordChatExporter.Core.Services.DataService.<GetGuildChannelsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CliFx.CliApplication.<HandleCommandExecutionAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CliFx.CliApplication.<RunAsync>d__14.MoveNext()`
OS: Windows 10 1903
.NET version 4.8

**Comment by RenanYudi** [comment]
Can you please paste the command you're running? Don't forget to redact the token

**Comment by dudeamax99** [comment]
Running this in the folder I have it installed in `.\DiscordChatExporter.Cli.exe exportguild -t <Censored User Token> -f HtmlDark -guild 590206783986073622 -o "D:\Documents\Chat Logs\2019-11-16 1914 EDT"

**Comment by RenanYudi** [comment]
Try
```
.\DiscordChatExporter.Cli.exe exportguild -t TOKEN -f HtmlDark -g 590206783986073622 -o "D:\Documents\Chat Logs\2019-11-16 1914 EDT
```

**Comment by dudeamax99** [comment]
Thank you, it now works.
If I may ask. why does using `-g` instead of `-guild` fix the http error?

**Comment by RenanYudi** [comment]
Because it's actually `--guild` :p

**Comment by dudeamax99** [comment]
Oh yeah I forgot that.
Really sick rn and not thinking right, thanks for the help

**Comment by RenanYudi** [comment]
No problem! I hope you get better soon :-)

**Comment by Tyrrrz** [comment]
Thanks @RenanYudi
