### ISSUE TITLE
Error HTTP status code: Forbidden - FORBIDDEN

### ISSUE THREAD

**Issue by cryptotrade3** [Tyrrrz/DiscordChatExporter#273]
I'm using the docker version on ubuntu 18.04. When I write 
  
`dotnet DiscordChatExporter.Cli.dll export -t [my_bot_token] -b -c [my_channell_id] `

I get this message:

```
DiscordChatExporter.Core.Services.Exceptions.HttpErrorStatusCodeException: Error HTTP status code: Forbidden - FORBIDDEN
   at DiscordChatExporter.Core.Services.DataService.GetApiResponseAsync(AuthToken token, String route) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core.Services\DataService.cs:line 61
   at DiscordChatExporter.Core.Services.DataService.GetChannelAsync(AuthToken token, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core.Services\DataService.cs:line 79
   at DiscordChatExporter.Cli.Commands.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportCommandBase.cs:line 66
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 19
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)


```

**Comment by Tyrrrz** [comment]
Are you sure that the token is valid and that the bot has access to the specified channel?

**Comment by cryptotrade3** [comment]
Yes my token is valid, but how can I ensure that the bot can access the server and the specific channel?

I tried to use this url https://discordapp.com/api/oauth2/authorize?scope=bot&client_id=XXX  with my id bot client, but it only seems useful to connect the bot to MY server. 

My goal is instead to export messages from a server not owned by me.

**Comment by Tyrrrz** [comment]
Not sure how to test it to be honest, but 403 almost certainly means it doesn't have access.

**Comment by Tyrrrz** [comment]
Haven't seen this happen. I'd assume you'd just enter the newest one in that case.
