### ISSUE TITLE
Commands fail with scheme being empty

### ISSUE THREAD

**Issue by jakubgs** [Tyrrrz/DiscordChatExporter#286]
I'm trying to use the docker image but it's failing with weird errors I don't understand:
```
 $ docker run --rm -it -e TOKEN="MY_TOKEN" tyrrrz/discordchatexporter channels --token $TOKEN --guild 1234567890
System.ArgumentException: The value cannot be null or empty. (Parameter 'scheme')
   at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
   at System.Net.Http.Headers.AuthenticationHeaderValue..ctor(String scheme, String parameter)
   at System.Net.Http.Headers.AuthenticationHeaderValue..ctor(String scheme)
   at DiscordChatExporter.Core.Services.DataService.<>c__DisplayClass4_0.<<GetApiResponseAsync>b__0>d.MoveNext() in /src/DiscordChatExporter.Core.Services/DataService.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at DiscordChatExporter.Core.Services.DataService.GetApiResponseAsync(AuthToken token, String route, Boolean errorOnFail) in /src/DiscordChatExporter.Core.Services/DataService.cs:line 51
   at DiscordChatExporter.Core.Services.DataService.GetApiResponseAsync(AuthToken token, String route) in /src/DiscordChatExporter.Core.Services/DataService.cs:line 46
   at DiscordChatExporter.Core.Services.DataService.GetGuildChannelsAsync(AuthToken token, String guildId) in /src/DiscordChatExporter.Core.Services/DataService.cs:line 140
   at DiscordChatExporter.Cli.Commands.GetChannelsCommand.ExecuteAsync(IConsole console) in /src/DiscordChatExporter.Cli/Commands/GetChannelsCommand.cs:line 23
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```
What does this mean?

**Comment by Tyrrrz** [comment]
Looks like token being passed is null. Are you sure `$TOKEN` retrieves the value you expect it to?

**Comment by Tyrrrz** [comment]
I reproduced the exact issue you have with the snippet you gave me, but if I change `$TOKEN` to the literal value of my token then it works correctly.

**Comment by Tyrrrz** [comment]
Note that `-e ...` sets an environment variable inside the container, while `$TOKEN` tries to read it from the current environment, i.e. the host machine (I'm pretty sure).

**Comment by jakubgs** [comment]
Oh, you're right. I misunderstood how to handle the env variables in Docker commands.

But wouldn't it make sense to add a check that verifies if an input like token is not an empty string?

**Comment by Tyrrrz** [comment]
It would, yeah.
I created a separate issue for it https://github.com/Tyrrrz/CliFx/issues/47
