### ISSUE TITLE
DiscordChatExporterException: Not found.

### ISSUE THREAD

**Issue by nicolashernandez** [Tyrrrz/DiscordChatExporter#310]
Hi

This should not be an issue. But I cannot find the right usage.
I am on ubuntu 18.04, I installed .NET runtime 3.1 and also the SDK.
Since I did not found any explanations (because of the following troubles), I have unzipped in the same dir : the Source code (zip), DiscordChatExporter.zip, DiscordChatExporter.CLI.zip. All come from downloaded from https://github.com/Tyrrrz/DiscordChatExporter/releases/tag/2.20

The following command works `dotnet DiscordChatExporter.Cli.dll` and gives me  `DiscordChatExporter.Cli v2.20.0.0 ...`

But after defining TOKEN and CHANNEL variables, when running  
`dotnet DiscordChatExporter.Cli.dll export -t $TOKEN -c $CHANNEL`

I got this 
```
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Not found.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 78
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 194
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 55
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)

```
I am sure I have missed something. I am not used to .net and I do not know or understand how to specify the dll to the dotnet command. 

Any help would be very appreciated !

Best

**Comment by Tyrrrz** [comment]
Not found would signify that the channel with the specified ID does not actually exist.

**Comment by nicolashernandez** [comment]
=/ 
First thanks for answering me so quickly.

Indeed I have just tested with a wring TOKEN and I ve got `DiscordChatExporterException: Authentication token is invalid.`
So at least my token is correct.

I ve tried alternative channels ids all obtained by clicking the "Copy ID" after enabling the developer mode. Same result.

So I ve attempted to get the ids from console tab (window.location.href). The first long sequence of number inside the url (as mentioned in step 5 of section "
How to get a Direct Message Channel ID" https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-a-server-id-or-a-server-channel-id) gave me the same ids as previous. 

But surprisingly, the SECOND sequence (on the right) lead me to successfully export the specified message channel...

So it is progressing but still not exactly working as expected. By chance have you got a server channel ID, that I could test ?  Or any Idea why there is something wrong with my channel IDs ?

Thank you in advance

**Comment by Tyrrrz** [comment]
Are you trying to export a DM channel or a regular channel?

**Comment by nicolashernandez** [comment]
... my mistake. I realize there are various options and corresponding commands. It works fine !
with `dotnet DiscordChatExporter.Cli.dll exportguild -t $TOKEN  -g $CHANNELID `

Thank you for your assistance

**Comment by Tyrrrz** [comment]
`exportguild` just exports all channels in a guild (server), so if it worked, it actually means that your `$CHANNELID` was in fact `$GUILDID`.

**Comment by nicolashernandez** [comment]
yes !
