### ISSUE TITLE
MacOS DCE CLI: Can't retreive html due to Terminal error

### ISSUE THREAD

**Issue by Vishisht182** [Tyrrrz/DiscordChatExporter#319]
I installed the .NET runtime and the dotnet command is showing. i copied the token and channel and this is my error output:

`DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Not found.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 78
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 194
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 55
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)`

Does this have to do with how im entering my arguments? or that the token and channel ID i entered are invalid?

**Comment by Tyrrrz** [comment]
It indicates that everything works, but the channel you wanted to retrieve does not exist.
