### ISSUE TITLE
Legitimately obtained token throws DiscordChatExporterException.Forbidden()

### ISSUE THREAD

**Issue by jacobroly** [Tyrrrz/DiscordChatExporter#330]
Hello, 

here is the command I tried to run.

``` /usr/local/share/dotnet/dotnet DiscordChatExporter.Cli.dll export -t "mY.AuTh.T0ken" -c 546380862288035880 -f Json```

and here is what the command returned:

```
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Access is forbidden.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 72
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelCategoryAsync(String channelParentId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 181
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 190
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```

I obtained the token that I have naturally, through the Google Chrome developer "network" tab -> search for "science" method. I am running Mac OS X 10.15.5.

**Comment by Tyrrrz** [comment]
Forbidden means you don't have access to the guild/channel.

**Comment by jacobroly** [comment]
I have access to the channel from within the discord client itself, though. What could be wrong?

**Comment by Tyrrrz** [comment]
You might not have permissions to read history or something. Is it this a bot or a user token?

**Comment by jacobroly** [comment]
A user token. I have permissions to read history in the actual channel (I was able to view the first message in the entire channel, even)

**Comment by Tyrrrz** [comment]
Does it work on other channels? Or channels in another guild?

**Comment by jacobroly** [comment]
It works on channels in another, much smaller server/guild. But in the guild I want to download from, things seem to work intermittently. Like, I have full perms to all the channels, but some of them return with Forbidden for no distinguishable reason.

The guild I'm downloading from is a discord partnered server, if that makes any difference.

**Comment by Tyrrrz** [comment]
I think another reason why it may return Forbidden is when Discord for some reason needs you to fill out a CAPTCHA. Usually logging in through the app first helps with that.

**Comment by elig0n** [comment]
I experience the same thing on Linux with token obtained from Network->Local Storage. 

The problematic requested channel has this symbol: ![image](https://user-images.githubusercontent.com/31196036/89710719-2bb3ab80-d98e-11ea-9d04-0e826404d8d8.png)

while other channels with a "clean" `#` symbol from the same guild are fetched alright.
