### ISSUE TITLE
Error Thrown When Mass-Exporting

### ISSUE THREAD

**Issue by ALEEF02** [Tyrrrz/DiscordChatExporter#331]
I am currently trying to export to a JSON. I tried to partition by every 100,000 messages. It appeared to be working until about 65% when I got:
```
System.InvalidOperationException: ']' is invalid without a matching open.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource, Int32 currentDepth, Byte token, JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonWriter.ValidateEnd(Byte token)
   at System.Text.Json.Utf8JsonWriter.WriteEndSlow(Byte token)
   at System.Text.Json.Utf8JsonWriter.WriteEnd(Byte token)
   at System.Text.Json.Utf8JsonWriter.WriteEndArray()
   at DiscordChatExporter.Domain.Exporting.Writers.JsonMessageWriter.WritePostambleAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\JsonMessageWriter.cs:line 249
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ResetWriterAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 33
   at DiscordChatExporter.Domain.Exporting.MessageExporter.DisposeAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 70
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__DisplayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 29
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMultipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportGuildCommand.cs:line 18
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```
I checked, and the partitions were never created. The JSON files got to roughly ~5 MB, and then stop. There are no other partitions insight. Should I re-run with a smaller partition number?

**Comment by Tyrrrz** [comment]
That looks weird. Try a smaller number.

**Comment by BamButz** [comment]
For anyone coming along here, check your drive space. ;)

**Comment by ALEEF02** [comment]
Yeah, I have over a TB free. That's not the issue

**Comment by BamButz** [comment]
> Yeah, I have over a TB free. That's not the issue

Actually you're right.
Which OS do you use? 
I've got the problem on my linux VM, on my workstation it works which is running windows.

**Comment by ALEEF02** [comment]
Windows 10 Home edition
