### ISSUE TITLE
Need help with the CLI

### ISSUE THREAD

**Issue by JustStanix** [Tyrrrz/DiscordChatExporter#342]
So basically I want to use this with my discord bot. The easiest solution I came up with was adding the CLI into my directory and then using shelljs to execute the command in js but I get this error everytime.

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: Path
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments)
   at DiscordChatExporter.Cli.Program.Main(String[] args) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Program.cs:line 9
   at DiscordChatExporter.Cli.Program.<Main>(String[] args)
```

```js
shell.exec(
          `dotnet ./ChatExporter/DiscordChatExporter.Cli.dll export -t ${process.env.BOT_TOKEN} -b -c ${reaction.message.channel.id} -f HtmlDark -o "../${user.username}'s Ticket - ${today}.html"`,
          function (code, stdout, stderr) {
            console.log("Exit code:", code);
            console.log("Program output:", stdout);
            console.log("Program stderr:", stderr);
          }
        );
```

**Comment by Tyrrrz** [comment]
Interesting. This is a bug in the framework.
The error means that there are two environment variables with the same name, differing only in case. Try to remove one of the variables.

**Comment by Tyrrrz** [comment]
This is fixed upstream, will be fixed in DCE in next release.
