### ISSUE TITLE
Unexpected exception when calling ResolveUrl

### ISSUE THREAD

**Issue by tybug** [Tyrrrz/DiscordChatExporter#344]
I get this error when loading a channel:

```
dotnet DiscordChatExporter.Cli.dll export -t TOKEN -c CHANNEL --media -o ../discord_export_07\:27\:2020/ --after "2019-10-17 00:00"
Exporting channel 'talk / coding'... 0.54%<input>(127,101) : error : Unexpected exception when calling ResolveUrl
```

it always happens at the same spot. The message it's trying to load when it errors contains only this link (ironically linking to github):
`https://github.com/mpv-player/mpv/commit/1e70e82baa9193f6f027338b0fab0f5078971fbe`

but I can't see anything wrong with it, other than the image in the embed for that url is exceptionally long: https://camo.githubusercontent.com/e46a1e2aa94a0a696a3360ab105beaf0473f13b9/68747470733a2f2f302e67726176617461722e636f6d2f6176617461722f34316461376562326136616530343034333836643838366538613761393138373f643d68747470732533412532462532466769746875622e6769746875626173736574732e636f6d253246696d6167657325324667726176617461727325324667726176617461722d757365722d3432302e706e6726723d6726733d323030

Possibly related to #332  ?

**Comment by Tyrrrz** [comment]
Probably hitting the file name limit :/

**Comment by tybug** [comment]
I'm on macos, which seems to be able to save the file fine if I do it manually

**Comment by Tyrrrz** [comment]
Does it also happen on a build from here?

https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/187439080

**Comment by tybug** [comment]
```csharp
 ~/Desktop/DiscordChatExporter.CLI 2 λ dotnet DiscordChatExporter.Cli.dll export -t TOKEN -c CHANNEL --media -o ../discord_export_07\:27\:2020/ --after "2019-10-17 00:00"
Exporting channel 'talk / coding'... 0.54%System.IO.PathTooLongException: The path '/Users/tybug/Desktop/discord_export_07:27:2020/REDACTED - talk - coding [474721485102120985] (after 2019-10-17).html_Files/68747470733a2f2f302e67726176617461722e636f6d2f6176617461722f34316461376562326136616530343034333836643838366538613761393138373f643d68747470732533412532462532466769746875622e6769746875626173736574732e636f6d253246696d6167657325324667726176617461727325324667726176617461722d757365722d3432302e706e6726723d6726733d323030' is too long, or a component of the specified path is too long.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at DiscordChatExporter.Domain.Internal.Extensions.HttpClientExtensions.DownloadAsync(HttpClient httpClient, String uri, String outputFilePath) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Internal\Extensions\HttpClientExtensions.cs:line 13
   at DiscordChatExporter.Domain.Internal.Extensions.HttpClientExtensions.DownloadAsync(HttpClient httpClient, String uri, String outputFilePath) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Internal\Extensions\HttpClientExtensions.cs:line 16
   at DiscordChatExporter.Domain.Exporting.MediaDownloader.DownloadAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MediaDownloader.cs:line 36
   at DiscordChatExporter.Domain.Exporting.ExportContext.ResolveMediaUrlAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ExportContext.cs:line 70
   at DiscordChatExporter.Domain.Exporting.Writers.Html.MiniRazorTemplate.ExecuteAsync()
   at MiniRazor.MiniRazorTemplateDescriptor.RenderAsync(Object model)
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WriteMessageGroupAsync(MessageGroup messageGroup) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 41
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WritePostambleAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 72
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ResetWriterAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 33
   at DiscordChatExporter.Domain.Exporting.MessageExporter.DisposeAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 70
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, Guild guild, Channel channel) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 56
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, Channel channel) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 63
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 69
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.HandleCommandExecutionAsync(ApplicationSchema applicationSchema, CommandLineInput commandLineInput, IReadOnlyDictionary`2 environmentVariables)
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```

**Comment by Tyrrrz** [comment]
Perhaps your Mac can save a file with a long file name, but .NET seemingly can't :P

**Comment by tybug** [comment]
I was mistaken earlier - when saving that image, macos truncates it to 240 characters long (`68747470733a2f2f302e67726176617461722e636f6d2f6176617461722f34316461376562326136616530343034333836643838366538613761393138373f643d68747470732533412532462532466769746875622e6769746875626173736574732e636f6d253246696d61676573253246677261766174.png`), instead of the full 355 character long string

**Comment by Tyrrrz** [comment]
We can truncate the file name too, but if the whole file path (including directory) exceeds a certain limit, it will still be bad. I'll make it so that it truncates it to 50 characters to have some leeway.

**Comment by Tyrrrz** [comment]
Try this build (once it finishes):

https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/187488733

**Comment by tybug** [comment]
works great. Thanks for maintaining this tool
