### ISSUE TITLE
Docker error: Requested resource does not exist

### ISSUE THREAD

**Issue by pauloabq** [Tyrrrz/DiscordChatExporter#356]
I'm on windows 10 
Docker version 19.03.12, build 48a66213fe

I can run:
`docker run --rm tyrrrz/discordchatexporter:stable`

result:

```
DiscordChatExporter.Cli v2.21.2

Usage
  dotnet DiscordChatExporter.Cli.dll [command] [options]

Options
  -h|--help         Shows help text.
  --version         Shows version information.

Commands
  export            Export a channel.
  exportdm          Export all direct message channels.
  exportguild       Export all channels within specified guild.
  channels          Get the list of channels in specified guild.
  dm                Get the list of direct message channels.
  guilds            Get the list of accessible guilds.
  guide             Explains how to obtain token, guild or channel ID.

You can run `dotnet DiscordChatExporter.Cli.dll [command] --help` to show help on a specific command.
```

But when running:

`docker run --rm -v d:\log:/app/out tyrrrz/discordchatexporter:stable export -t <TOKEN> -c <CHANNELID> `

(`<TOKEN>` (a string 59 length) and `<CHANNELID>` (string 18 length) values obtained as described here: https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs)
got this: 

```
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Requested resource does not exist.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line 72
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line 187
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in /src/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in /src/DiscordChatExporter.Cli/Commands/ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```
tried in differents channel ids

**Comment by Yudi** [comment]
This usually means that the chat doesn't exist (404 not found). Are you copying the IDs correctly? If you're trying to export DMs, make sure you're not copying the user ID.

#
Olá! Geralmente isso significa que o canal não existe, a API retorna 404. Você está copiando os IDs corretamente? Se você está tentando exportar mensagens diretas (DM), assegure-se de não estar copiando o ID de usuário.<br>
Vou manter ± nos dois idiomas pra poder ajudar outras pessoas, mas pode me responder em inglês.

**Comment by pauloabq** [comment]
That's the point... I was copying out serverid:(
Thanks!
