### ISSUE TITLE
Media export fails with TaskCanceledException

### ISSUE THREAD

**Issue by coletonodonnell** [Tyrrrz/DiscordChatExporter#372]
Input:
`dotnet DiscordChatExporter.Cli.dll exportguild -t "my_user_token" -g my_valid_guild_id -o "e_b backup, creation - 20200831 @ 22:49" --media`

Output:
```
Exporting 7 channels... 0.00%System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at DiscordChatExporter.Domain.Internal.Extensions.HttpClientExtensions.DownloadAsync(HttpClient httpClient, String uri, String outputFilePath) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Internal\Extensions\HttpClientExtensions.cs:line 17
   at DiscordChatExporter.Domain.Exporting.MediaDownloader.DownloadAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MediaDownloader.cs:line 37
   at DiscordChatExporter.Domain.Exporting.ExportContext.ResolveMediaUrlAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ExportContext.cs:line 92
   at DiscordChatExporter.Domain.Exporting.Writers.Html.MiniRazorTemplate.ExecuteAsync()
   at MiniRazor.MiniRazorTemplateDescriptor.RenderAsync(Object model)
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WriteMessageGroupAsync(MessageGroup messageGroup) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 44
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WritePostambleAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 72
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ResetWriterAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 33
   at DiscordChatExporter.Domain.Exporting.MessageExporter.DisposeAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 70
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__DisplayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 29
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMultipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportGuildCommand.cs:line 18
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```

It throws the same error for each command, no matter if it is bot or user. It does download most of the guild, but stopped at around July of this year in at least the file I looked at. It did reach "100%" really fast after about 75%, then reset back to 0.00% and threw the error (I don't know if it was in that specific order.)

**Comment by Tyrrrz** [comment]
Looks like the error is not related to token.

I assume from your description that the problem is easily reproducible? Can you pinpoint the exact message it tumbles on to see if there's anything special about it?

**Comment by coletonodonnell** [comment]
Sure, I can list what each it stopped on. All of the channels minus one were successful, the one that wasn't was the "speak" channel. It stopped at a YouTube video, it was the following video:
https://youtu.be/tcqVmavMN9M

I am going to delete it and then try again.

**Comment by coletonodonnell** [comment]
Okay, so after deleting that link, it seems that it went like 3 or 4 messages ahead, and then hit the bucket as well:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at DiscordChatExporter.Domain.Internal.Extensions.HttpClientExtensions.DownloadAsync(HttpClient httpClient, String uri, String outputFilePath) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Internal\Extensions\HttpClientExtensions.cs:line 17
   at DiscordChatExporter.Domain.Exporting.MediaDownloader.DownloadAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MediaDownloader.cs:line 37
   at DiscordChatExporter.Domain.Exporting.ExportContext.ResolveMediaUrlAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ExportContext.cs:line 92
   at DiscordChatExporter.Domain.Exporting.Writers.Html.MiniRazorTemplate.ExecuteAsync()
   at MiniRazor.MiniRazorTemplateDescriptor.RenderAsync(Object model)
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WriteMessageGroupAsync(MessageGroup messageGroup) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 44
   at DiscordChatExporter.Domain.Exporting.Writers.HtmlMessageWriter.WritePostambleAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\HtmlMessageWriter.cs:line 72
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ResetWriterAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 33
   at DiscordChatExporter.Domain.Exporting.MessageExporter.DisposeAsync() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 70
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__DisplayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 29
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMultipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportGuildCommand.cs:line 18
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```
This was the stack trace, which seems to be the same as the last one but I can't read them well so. The image before these messages is entitled:
20200717165230_1.jpg

**Comment by Tyrrrz** [comment]
Can you open the image it browser just fine? Can you share the URL?

**Comment by coletonodonnell** [comment]
It opens from the html file just fine, and it opens fine via cdn. I would rather not, as it contains one of my user names online. I can message it to you via your twitter if you'd like?

**Comment by Tyrrrz** [comment]
If you can, please do. My twitter nickname is the same as here.
