### ISSUE TITLE
Having trouble with exporting a DM.

### ISSUE THREAD

**Issue by leewensim** [Tyrrrz/DiscordChatExporter#374]
The exporter works when I use the exportguild command, but not when I'm trying to export a channel using the CLI (specifically a DM).

Here's the command I'm using to run the exporter (on MacOS):

> dotnet DiscordChatExporter.Cli.dll export -c CHANNELID -t TOKEN

Where CHANNELID and TOKEN are replaced appropriately.

And the error message:
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Requested resource does not exist.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 72
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 187
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)

**Comment by Yudi** [comment]
Make sure you're copying the [DM ID](https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs#how-to-get-a-direct-message-channel-id), not the user ID.

**Comment by leewensim** [comment]
Ack, thank you for the quick reply! That was the problem.
