### ISSUE TITLE
Is there way to save all message from an user?

### ISSUE THREAD

**Issue by cjlaborde** [Tyrrrz/DiscordChatExporter#384]
I copy id and when I try to extract info it does not work.

![gnome-shell-screenshot-2FIIR0](https://user-images.githubusercontent.com/40572114/94084674-124aaf80-fdd4-11ea-87de-92d1776f0e8f.png)
```
dotnet DiscordChatExporter.Cli.dll export -t "NDMyOTUwNDY0ODkyMzcwOTQ0.XmidnA.liPl32TzzZ3pykyBE9nt0oUKqgk" -c 432950464892370944                  
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Requested resource does not exist.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 72
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 187
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)

```

**Comment by Tyrrrz** [comment]
Do you mean DMs?

**Comment by cjlaborde** [comment]
> Do you mean DMs?
I mean all the posts that an user has made on a server.
![image](https://user-images.githubusercontent.com/40572114/94489765-118a9280-01b3-11eb-8586-7fbf5b724449.png)
One way is to use search and use from:username#1245

**Comment by Tyrrrz** [comment]
Ah, I see. Not currently. This should be covered by #160 which is more generic. Not sure whether it will ever be implemented though.
