### ISSUE TITLE
Unable to export private channels

### ISSUE THREAD

**Issue by fmlatghor** [Tyrrrz/DiscordChatExporter#397]
OS: Fedora Linux 32

```zsh
% dotnet DiscordChatExporter.Cli.dll export -t <token> -c <channel id> -o discord
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Requested resource does not exist.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 72
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 187
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)```

**Comment by fmlatghor** [comment]
I'm able to export group chats; do I need to write a self-bot instead?

**Comment by andrewkolos** [comment]
I was unable to reproduce this on 2.23. Here is what I did:
* Opened up Discord and opened up my dummy test server.
* Created a new text channel and edited it.
* Removes all permissions from `@everyone` and gave all permissions to my test user (who does not own the server) all permissions.
* Opened up DCE GUI, signed in as that test user, and exported the channel.

Note I did use the GUI but I doubt that should change anything.

**Comment by Tyrrrz** [comment]
Related/duplicate: #356

**Comment by fmlatghor** [comment]
Ok I actually figured out what was wrong. When I was copying ids from private channels, I was copying the user id and not the channel id. I'm not sure if I just didn't read something on the guide.

**Comment by Tyrrrz** [comment]
Unsurprisingly, the same mistake as the one in the issue I linked ;)
