### ISSUE TITLE
Skip getting channel category if access is forbidden

### ISSUE THREAD

**Issue by mikeminutillo** [Tyrrrz/DiscordChatExporter#426]
Frequently I want to export a channel that I have access to but I am missing some permission on the channel category and the tool throws an exception:

```
DiscordChatExporter.Domain.Exceptions.DiscordChatExporterException: Access is forbidden.
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line 72
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelCategoryAsync(String channelParentId) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line 181
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(String channelId) in /src/DiscordChatExporter.Domain/Discord/DiscordClient.cs:line 190
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in /src/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:line 68
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in /src/DiscordChatExporter.Cli/Commands/ExportChannelCommand.cs:line 14
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```

Would it be possible to ignore this exception and export the channel without the channel category information?

**Comment by mikeminutillo** [comment]
I figured out this is just the read permission on the channel category. Quite a few of the discords I am in give read access to specific channels within a category but not to the category itself.

**Comment by RushSh** [comment]
I would like to work on this issue.

**Comment by Tyrrrz** [comment]
@RushSh go ahead
