### ISSUE TITLE
[CLI] Error when using `--media` and/or `--reuse-media`

### ISSUE THREAD

**Issue by evandrix** [Tyrrrz/DiscordChatExporter#434]
```
Exporting channel '<redacted> / <redacted>'... 0.00%
ERROR: System.ArgumentException: The path is empty. (Parameter 'relativeTo')
  at System.IO.Path.GetRelativePath(String relativeTo, String path, StringComparison comparisonType)
  at System.IO.Path.GetRelativePath(String relativeTo, String path)
  at DiscordChatExporter.Domain.Exporting.ExportContext.ResolveMediaUrlAsync(String url) in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/ExportContext.cs:78
  at DiscordChatExporter.Domain.Exporting.Writers.JsonMessageWriter.WritePreambleAsync() in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/Writers/JsonMessageWriter.cs:186
  at DiscordChatExporter.Domain.Exporting.MessageExporter.GetWriterAsync() in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/MessageExporter.cs:60
  at DiscordChatExporter.Domain.Exporting.MessageExporter.ExportMessageAsync(Message message) in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/MessageExporter.cs:65
  at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/ChannelExporter.cs:56
  at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/ChannelExporter.cs:40
  at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in
    /DiscordChatExporter/DiscordChatExporter.Domain/Exporting/ChannelExporter.cs:62
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, Guild guild, Channel channel) in
    /DiscordChatExporter/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:68
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, Channel channel) in
    /DiscordChatExporter/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:75
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, String channelId) in
    /DiscordChatExporter/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs:81
  at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in
    /DiscordChatExporter/DiscordChatExporter.Cli/Commands/ExportChannelCommand.cs:16
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```

**Comment by Tyrrrz** [comment]
Are you running it in the root of the drive or something?

**Comment by evandrix** [comment]
no, i redacted the path before it

**Comment by Tyrrrz** [comment]
Question: are you running in Docker and/or setting the `-o`/`--output` option manually?

**Comment by Tyrrrz** [comment]
Try the fixed version on CI: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/374578604
