### ISSUE TITLE
Crash: "Invalid Snowflake" on Linux

### ISSUE THREAD

**Issue by dl8bh** [Tyrrrz/DiscordChatExporter#478]
DiscordChatExporter crashes with the message "Invalid Snowlake"

dotnet DiscordChatExporter.Cli.dll exportall -o /some/folder --token SomeDiscordToken

System.FormatException: Invalid snowflake: <31 DIGIT LONG INT VAULE>.
   at DiscordChatExporter.Domain.Discord.Snowflake.Parse(String str, IFormatProvider formatProvider) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\Snowflake.cs:line 51
   at DiscordChatExporter.Domain.Exporting.Writers.MarkdownVisitors.PlainTextMarkdownVisitor.VisitMention(MentionNode mention) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\MarkdownVisitors\PlainTextMarkdownVisitor.cs:line 50
   at DiscordChatExporter.Domain.Markdown.MarkdownVisitor.Visit(MarkdownNode node) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Markdown\MarkdownVisitor.cs:line
36
   at DiscordChatExporter.Domain.Markdown.MarkdownVisitor.Visit(IEnumerable`1 nodes) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Markdown\MarkdownVisitor.cs:line 41
   at DiscordChatExporter.Domain.Exporting.Writers.MarkdownVisitors.PlainTextMarkdownVisitor.Format(ExportContext context, String markdown) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\MarkdownVisitors\PlainTextMarkdownVisitor.cs:line 77
   at DiscordChatExporter.Domain.Exporting.Writers.CsvMessageWriter.WriteMessageAsync(Message message) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\CsvMessageWriter.cs:line 86
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ExportMessageAsync(Message message) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 68
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 56
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 40
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__DisplayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 34
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMultipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 71
   at DiscordChatExporter.Cli.Commands.ExportAllCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportAllCommand.cs:line 33
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables

**Comment by 96-LB** [comment]
This is the same bug as #474 - I'll try to PR a fix today
