### ISSUE TITLE
`System.FormatException: Invalid snowflake: 48746484646.`

### ISSUE THREAD

**Issue by l1ving** [Tyrrrz/DiscordChatExporter#505]
I'm getting the error `System.FormatException: Invalid snowflake: 48746484646.` each time I try to export this guild. I can consistently reproduce this issue after several re-tries, same stacktrace. Each time the export is close to being finished, but the total saved messages appears to be `805730` *each* retry, while my guild has at least `1280742` messages.

If there is any way I can help debug this I would be greatful, because despite the exporter being around 98% "done" when it happens, I only have `62.9%` of the messages saved...

I am running version `v2.26.0` on Arch Linux.

Command:
```
discord-chat-exporter-cli exportguild -b -t "$DISCORD_TOKEN_BOT" -g 573954110454366214 --dateformat "yyyy/MM/dd HH:mm" --parallel 4 -f Csv
```

Stacktrace:
```
ERROR: System.FormatException: Invalid snowflake: 48746484646.
   at DiscordChatExporter.Domain.Discord.Snowflake.Parse(String str, IFormatProvider formatProvider) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\Snowflake.cs:line 51
   at DiscordChatExporter.Domain.Exporting.Writers.MarkdownVisitors.PlainTextMarkdownVisitor.VisitMention(MentionNode mention) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\MarkdownVisitors\PlainTextMarkdownVisitor.cs:line 50
   at DiscordChatExporter.Domain.Markdown.MarkdownVisitor.Visit(MarkdownNode node) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Markdown\MarkdownVisitor.cs:line 36
   at DiscordChatExporter.Domain.Markdown.MarkdownVisitor.Visit(IEnumerable`1 nodes) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Markdown\MarkdownVisitor.cs:line 41
   at DiscordChatExporter.Domain.Exporting.Writers.MarkdownVisitors.PlainTextMarkdownVisitor.Format(ExportContext context, String markdown) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\MarkdownVisitors\PlainTextMarkdownVisitor.cs:line 77
   at DiscordChatExporter.Domain.Exporting.Writers.CsvMessageWriter.WriteMessageAsync(Message message) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\Writers\CsvMessageWriter.cs:line 86
   at DiscordChatExporter.Domain.Exporting.MessageExporter.ExportMessageAsync(Message message) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\MessageExporter.cs:line 68
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 56
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 40
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__DisplayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 34
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMultipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 71
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportGuildCommand.cs:line 19
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```

**Comment by Tyrrrz** [comment]
Can you please try latest CI build?
https://github.com/Tyrrrz/DiscordChatExporter#download

**Comment by 96-LB** [comment]
This should be fixed in the latest stable release (`v2.26.1`) as well.

**Comment by l1ving** [comment]
I have updated to `v2.26.1` and am currently re-running that guild, will let you know how this goes
```
discord_kamiblue_backup % discord-chat-exporter-cli exportguild -b -t "$DISCORD_TOKEN_BOT" -g 573954110454366214 --dateformat "yyyy/MM/dd HH:mm" --parallel 4 -f Csv
Exporting 71 channels... 98.86%
```

**Comment by l1ving** [comment]
```
discord_kamiblue_backup % discord-chat-exporter-cli exportguild -b -t "$DISCORD_TOKEN_BOT" -g 573954110454366214 --dateformat "yyyy/MM/dd HH:mm" --parallel 4 -f Csv
Exporting 71 channels... 0.00%ERROR: System.Threading.Tasks.TaskCanceledException: The operation was canceled.                                                          
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DiscordChatExporter.Domain.Discord.DiscordClient.<>c__DisplayClass5_0.<<GetResponseAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 34
   at DiscordChatExporter.Domain.Discord.DiscordClient.TryGetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 67
   at DiscordChatExporter.Domain.Discord.DiscordClient.TryGetGuildMemberAsync(Snowflake guildId, User user) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 170
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 48
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 40
   at DiscordChatExporter.Domain.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Exporting\ChannelExporter.cs:line 62
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.<>c__DisplayClass4_0.<<ExportMultipleAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 34
   at DiscordChatExporter.Cli.Commands.Base.ExportMultipleCommandBase.ExportMultipleAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportMultipleCommandBase.cs:line 71
   at DiscordChatExporter.Cli.Commands.ExportGuildCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportGuildCommand.cs:line 19
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)
```
I'm getting this now, for some reason. Reran it twice and it happened both times.

**Comment by Tyrrrz** [comment]
Looks like some network connectivity issue.

**Comment by l1ving** [comment]
Yea, probably on my end then. Thanks
