### ISSUE TITLE
DiscordChatExporter.Cli.dll  cannot request

### ISSUE THREAD

**Issue by summer091994** [Tyrrrz/DiscordChatExporter#535]
after you update your program a few days ago, the DiscordChatExporter.Cli.dll   cannot work.

error:
ERROR: System.Threading.Tasks.TaskCanceledException: The operation was canceled.

**Comment by Tyrrrz** [comment]
What was the command?

**Comment by summer091994** [comment]
I want to use the .dll  to pull data, but it cannot work. Before you update the program, its fine, after 03/24/2021,i cannot pull data.
Is there anything i need to  update?

**Comment by summer091994** [comment]
sorry，it seems like my IP is blocked.....Dou you kown the discord platform how long will it be deblock?

**Comment by Tyrrrz** [comment]
No idea. Never had that.

**Comment by shanekong** [comment]
i encounter the same problem;  can anyone help me out?
my command line is :dotnet DiscordChatExporter.Cli.dll export -t "NzU5NTk5MDYzNzkxNDM1ODM2.X2_2Gw.5xxExkpoXtgtZ6qDNHv9KYhPqsQ"  -c 608562749991026688

the error logs is listed as follows:
ERROR: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DiscordChatExporter.Domain.Discord.DiscordClient.<>c__DisplayClass5_0.<<GetResponseAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 34
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 44
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetChannelAsync(Snowflake channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 192
   at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, Snowflake channelId) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:line 73
   at DiscordChatExporter.Cli.Commands.ExportChannelCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelCommand.cs:line 18
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables)

**Comment by Tyrrrz** [comment]
@shanekong sounds like connection timed out.
Can you successfully login to Discord in browser?

**Comment by shanekong** [comment]
I can login to Discord in browser,  and i have tried the same command line in windows use DiscordChatExporter.Cli.exe, it also works.

**Comment by Tyrrrz** [comment]
Not sure then. Maybe something is blocking your connection? Maybe firewall or antivirus?

**Comment by shanekong** [comment]
Thank you for your response. emm,  you are right, the connection is blocked by the web,  i have tried the command line in another linux machine, it can successfully work.
