### ISSUE TITLE
Doesn't work, crashes while starting up even with valid token

### ISSUE THREAD

**Issue by kimpurcell** [Tyrrrz/DiscordChatExporter#538]
The app just crashes while fetching something after entering the token. Has it worked for anyone lately?

**Comment by Tyrrrz** [comment]
You'd get better results if you tell us the exact error that happens

**Comment by kimpurcell** [comment]
Sure, here's the error. I entered the token and click the arrow button. Waited for minutes and then get this message.

System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DiscordChatExporter.Domain.Discord.DiscordClient.<>c__DisplayClass5_0.<<GetResponseAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 34
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 44
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetGuildChannelsAsync(Snowflake guildId)+MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Discord\DiscordClient.cs:line 112
   at DiscordChatExporter.Domain.Discord.DiscordClient.GetGuildChannelsAsync(Snowflake guildId)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.AggregateAsync[T](IAsyncEnumerable`1 asyncEnumerable) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 17
   at DiscordChatExporter.Domain.Utilities.AsyncExtensions.AggregateAsync[T](IAsyncEnumerable`1 asyncEnumerable) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Domain\Utilities\AsyncExtensions.cs:line 17
   at DiscordChatExporter.Gui.ViewModels.RootViewModel.PopulateGuildsAndChannels() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Gui\ViewModels\RootViewModel.cs:line 173
   at DiscordChatExporter.Gui.ViewModels.RootViewModel.PopulateGuildsAndChannels() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Gui\ViewModels\RootViewModel.cs:line 171
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Tyrrrz** [comment]
Looks like connection timed out. Check if anything is blocking traffic, like a firewall etc.
