### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Could not find color or style 'Serious'.

### ISSUE THREAD

**Issue by billsquare1** [Tyrrrz/DiscordChatExporter#557]
### Version

v.2.27.0 (osx)

### Flavor

CLI (Command Line Interface)

### Details

when i try to export the channel im trying to export, i get this error message and terminal crashes saying : dotnet quit unexpectedly. 

any help would be much appreciated 

i dont know if its relavant but this is the command im trying to do

dotnet DiscordChatExporter.Cli.dll export -t token -c  channel id -f PlainText --before 2021-03-05 --after 2021-03-02

this is the error message:

```
Fetching channel(s)...
Exporting 1 channel(s)...
Unhandled exception. System.InvalidOperationException: Could not find color or style 'Serious'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 16
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 26
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 37
   at Spectre.Console.TaskDescriptionColumn.Render(RenderContext context, ProgressTask task, TimeSpan deltaTime) in /_/src/Spectre.Console/Widgets/Progress/Columns/TaskDescriptionColumn.cs:line 23
   at Spectre.Console.DefaultProgressRenderer.<>c__DisplayClass13_1.<Update>b__1(ProgressColumn column) in /_/src/Spectre.Console/Widgets/Progress/Renderers/DefaultProgressRenderer.cs:line 98
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Spectre.Console.DefaultProgressRenderer.Update(ProgressContext context) in /_/src/Spectre.Console/Widgets/Progress/Renderers/DefaultProgressRenderer.cs:line 98
   at Spectre.Console.ProgressContext.Refresh() in /_/src/Spectre.Console/Widgets/Progress/ProgressContext.cs:line 76
   at Spectre.Console.ProgressRefreshThread.Run() in /_/src/Spectre.Console/Widgets/Progress/ProgressRefreshThread.cs:line 46
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Abort trap: 6
```

### Steps to reproduce

dotnet DiscordChatExporter.Cli.dll export -t token -c  channel id -f PlainText --before 2021-03-05 --after 2021-03-02

**Comment by Tyrrrz** [comment]
Thanks for reporting, I'll look into it.

**Comment by Tyrrrz** [comment]
Can't seem to reproduce it. Is there anything specific about the channels you are exporting? Do their names happen to include square brackets?

**Comment by billsquare1** [comment]
> Can't seem to reproduce it. Is there anything specific about the channels you are exporting? Do their names happen to include square brackets?

i tried with some different channels and the error was Unhandled exception. System.InvalidOperationException: Could not find color or style '**first word of the channel name**'.
im getting the error with all the channels i have tried to export

**Comment by 96-LB** [comment]
I dug into it and can confirm that square brackets are being interpreted as style tags by Spectre and cause this error. I was able to reproduce this by changing a category name from `Information` to `[Information]`. The program crashes when it tries to print the progress string (e.g. `[Information] / announcements  ----------------------------------------   0%`) and gets parsed by Spectre.  

> i tried with some different channels and the error was Unhandled exception. System.InvalidOperationException: Could not find color or style 'first word of the channel name'.

I don't know of any way to put brackets in a channel name, however. The original error posted also uses "Serious", which starts with a capital letter; that's also disallowed by Discord if I'm not mistaken. Are you sure you didn't mean the category name? If not, maybe there's something different going on here too.

As a small aside, this crash caused my terminal cursor to disappear. I'm assuming it was hidden by the console and never unhidden because of the early failure. I'm not sure if anything can be done, and ideally it would never surface if the program doesn't crash, but I wasn't able to fix it without a terminal restart which was annoying. I figured it's worth bringing up at least.

**Comment by billsquare1** [comment]
my mistake - it was the category name, and yeah they are in square brackets

**Comment by 96-LB** [comment]
https://github.com/Tyrrrz/DiscordChatExporter/blob/eb49d0bd16745a77ac7054e8a78e98b4855ae8d7/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs#L67

https://github.com/Tyrrrz/DiscordChatExporter/blob/eb49d0bd16745a77ac7054e8a78e98b4855ae8d7/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs#L116

https://github.com/Tyrrrz/DiscordChatExporter/blob/eb49d0bd16745a77ac7054e8a78e98b4855ae8d7/DiscordChatExporter.Cli/Commands/GetChannelsCommand.cs#L33

https://github.com/Tyrrrz/DiscordChatExporter/blob/eb49d0bd16745a77ac7054e8a78e98b4855ae8d7/DiscordChatExporter.Cli/Commands/GetDirectMessageChannelsCommand.cs#L30

I believe these are the four locations that can cause a crash. Though direct message category names cannot contain brackets, the channels can because usernames don't have the same restrictions as text channel names. Since Spectre provides a markup escape function, it'd be really easy to just apply that here (or just double all of the brackets ourselves), but since all the related code goes through the IConsole interface, I wasn't sure if hardcoding that for a specific implementation would be the ideal solution. I don't know how else to approach it, though, since IConsole/ConsoleWriter don't expose any methods for writing escaped text.

**Comment by Tyrrrz** [comment]
Thanks for looking into it @96-LB. Yeah, it seems my hunch was right. I actually tried to put square brackets in a channel name on a test server, but Discord wouldn't let me -- turns it out it was about categories after all.

Note that among the snippets you linked only this one is vulnerable to this issue:

https://github.com/Tyrrrz/DiscordChatExporter/blob/eb49d0bd16745a77ac7054e8a78e98b4855ae8d7/DiscordChatExporter.Cli/Commands/Base/ExportCommandBase.cs#L67

The others don't use Spectre.Console's console, but rather CliFx's console directly which doesn't do any special parsing.

Looking at the docs [here](https://spectreconsole.net/markup#escaping-format-characters) it seems we need to use `Markup.Escape(...)` on the task description passed to `StartTaskAsync`.

**Comment by Tyrrrz** [comment]
@billsquare1 can you test out the latest CI build with the fix? https://github.com/Tyrrrz/DiscordChatExporter#download

**Comment by Niektory** [comment]
I ran into this problem when trying to export a thread with a name containing square brackets.

Version: DiscordChatExporter.Cli v2.42.0
OS: Manjaro Linux 23.0.4

```
     Unhandled exception. System.InvalidOperationException: Could not find color or style 'ghjhjgh'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 29
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 42
   at Spectre.Console.TaskDescriptionColumn.Render(RenderOptions options, ProgressTask task, TimeSpan deltaTime) in /_/src/Spectre.Console/Live/Progress/Columns/TaskDescriptionColumn.cs:line 20
   at Spectre.Console.DefaultProgressRenderer.<>c__DisplayClass13_1.<Update>b__1(ProgressColumn column) in /_/src/Spectre.Console/Live/Progress/Renderers/DefaultProgressRenderer.cs:line 100
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Spectre.Console.DefaultProgressRenderer.Update(ProgressContext context) in /_/src/Spectre.Console/Live/Progress/Renderers/DefaultProgressRenderer.cs:line 101
   at Spectre.Console.ProgressContext.Refresh() in /_/src/Spectre.Console/Live/Progress/ProgressContext.cs:line 71
   at Spectre.Console.ProgressRefreshThread.Run() in /_/src/Spectre.Console/Live/Progress/ProgressRefreshThread.cs:line 45
```
