### ISSUE TITLE
System.NotSupportException with Encodings

### ISSUE THREAD

**Issue by YourMCGeek** [Tyrrrz/DiscordChatExporter#631]
### Version

2.28

### Flavor

CLI (Command Line Interface)

### Details

I was looking to export a channel of mine in the default HtmlDark format. I am using a bot token with the program. The command used to run the program is as follows:
```Bash
dotnet DiscordChatExporter.Cli.dll export -t [Omitted] -c 710271026277122069 -b
```

Upon running the command, I am presented with 
```Fetching channel(s)...
Exporting 1 channel(s)...
ERROR
System.NotSupportedException: No data is available for encoding 0. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
  at System.Text.Encoding.GetDataItem()
  at System.Text.Encoding.get_EncodingName()
  at Spectre.Console.AnsiConsoleFactory.Create(AnsiConsoleSettings settings) in \_\src\Spectre.Console\AnsiConsoleFactory.cs:57
  at Spectre.Console.AnsiConsole.Create(AnsiConsoleSettings settings) in \_\src\Spectre.Console\AnsiConsole.cs:67
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.CreateAnsiConsole(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:10
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.CreateProgressTicker(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:19
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExportAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:57
  at DiscordChatExporter.Cli.Commands.ExportChannelsCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelsCommand.cs:35
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:149
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:191
```

### Steps to reproduce

- Download 2.28 and unzip it
- Navigate into the new folder and run the command 
```Bash
dotnet DiscordChatExporter.Cli.dll export -t [Omitted] -c 710271026277122069 -b
```
*Replace the ID after -c with a appropriate channel ID the token has access too*
- Observe console

**Comment by Tyrrrz** [comment]
Hi, thanks for reporting.
Interesting. I assume it happens with other commands as well?

**Comment by YourMCGeek** [comment]
I've only tested with the export command as that is the only one I need for my current project, however I am more than able and willing to test with the other commands and Ill report back shortly.

**Comment by Tyrrrz** [comment]
I know it's a crude test, but can you drop overwrite your existing `CliFx.*` files with these and see if it works?

[CliFx.zip](https://github.com/Tyrrrz/DiscordChatExporter/files/6793430/CliFx.zip)

**Comment by YourMCGeek** [comment]
That worked for me with the export command both with HtmlDark and PlainText formats.

**Comment by Tyrrrz** [comment]
Nice, thank you.

**Comment by Tyrrrz** [comment]
By the way, what operating system were you running it on? Out of curiosity, because I couldn't reproduce it myself.

**Comment by YourMCGeek** [comment]
I was on my Windows 10 laptop, but my Windows 10 desktop seems to be fine without the zip file. Interesting, sorry!
