### ISSUE TITLE
Unable to login with token on CLI and GUI

### ISSUE THREAD

**Issue by n3rd3x3** [Tyrrrz/DiscordChatExporter#679]
### Version

2.30

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Details

I was expecting to be able to login with my token, however i got this on CLI:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
  at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  at DiscordChatExporter.Core.Discord.DiscordClient.<>c__DisplayClass5_0.<<GetResponseAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:41
  at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
  at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
  at DiscordChatExporter.Core.Discord.DiscordClient.GetResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:36
  at DiscordChatExporter.Core.Discord.DiscordClient.GetJsonResponseAsync(String url) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:46
  at DiscordChatExporter.Core.Discord.DiscordClient.GetGuildChannelsAsync(Snowflake guildId)+MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:114
  at DiscordChatExporter.Core.Discord.DiscordClient.GetGuildChannelsAsync(Snowflake guildId)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at DiscordChatExporter.Core.Utils.Extensions.AsyncExtensions.AggregateAsync[T](IAsyncEnumerable`1 asyncEnumerable) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\AsyncExtensions.cs:17
  at DiscordChatExporter.Core.Utils.Extensions.AsyncExtensions.AggregateAsync[T](IAsyncEnumerable`1 asyncEnumerable) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\AsyncExtensions.cs:17
  at DiscordChatExporter.Cli.Commands.GetDirectMessageChannelsCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\GetDirectMessageChannelsCommand.cs:17
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:149
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:191
```
and this on the GUI version:
![image](https://n3rd3x3.xyz/media/dotnet_kFGrxYJb9f.png)

### Steps to reproduce

On CLI:
- I attemped to do `dotnet DiscordChatExporter.Cli.dll dm -t "put token here"` and got the error after a few minutes

On GUI
- I entered my token and waited a few minutes, then got the error message

**Comment by n3rd3x3** [comment]
> Very weird. Are you running the GUI on macOS or is that just a skin?

Sorry for the late reply, its actually just a ShareX theme (its added after the screenshot is taken.) Sorry for the confusion.

**Comment by n3rd3x3** [comment]
I've gotten it to work again by resetting my network in the Windows settings.

**Comment by Tyrrrz** [comment]
Great :)
