### ISSUE TITLE
Error exporting channel(s)

### ISSUE THREAD

**Issue by SilSinn9801** [Tyrrrz/DiscordChatExporter#747]
### Version

2.31.0

### Flavor

GUI (Graphical User Interface), CLI (Command Line Interface)

### Export format

HTML, TXT, JSON, CSV

### Details

DCE 2.31.0 (in both GUI & CLI versions) returns an error message when trying to export a channel that contains more than 97500 messages, regardless of whether the before/after date/message option(s) is/are used or not. Example error message when choosing JSON as output format:
```
System.InvalidOperationException: Cannot read the specified JSON element as a non-empty and non-whitespace string value.
  at JsonExtensions.Reading.StringExtensions.GetNonWhiteSpaceString(JsonElement element) in \_\JsonExtensions\Reading\StringExtensions.cs:55
  at DiscordChatExporter.Core.Discord.Data.Emoji.Parse(JsonElement json) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Emoji.cs:51
  at DiscordChatExporter.Core.Utils.Extensions.GenericExtensions.Pipe[TIn,TOut](TIn input, Func`2 transform) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\GenericExtensions.cs:7
  at DiscordChatExporter.Core.Discord.Data.Reaction.Parse(JsonElement json) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Reaction.cs:11
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at DiscordChatExporter.Core.Discord.Data.Message.Parse(JsonElement json) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Message.cs:63
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at System.Linq.Enumerable.ReverseIterator`1.ToArray()
  at DiscordChatExporter.Core.Discord.DiscordClient.GetMessagesAsync(Snowflake channelId, Nullable`1 after, Nullable`1 before, IProgress`1 progress, CancellationToken cancellationToken)+MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\DiscordClient.cs:0
  at DiscordChatExporter.Core.Discord.DiscordClient.GetMessagesAsync(Snowflake channelId, Nullable`1 after, Nullable`1 before, IProgress`1 progress, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:45
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:45
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:80
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_2.<<ExecuteAsync>b__2>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:93
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.StartTaskAsync(ProgressContext progressContext, String description, Func`2 performOperationAsync) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:43
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_1.<<ExecuteAsync>b__1>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:75
  at DiscordChatExporter.Core.Utils.Extensions.AsyncExtensions.<>c__DisplayClass2_0`1.<<ParallelForEachAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\AsyncExtensions.cs:42
  at DiscordChatExporter.Core.Utils.Extensions.AsyncExtensions.ParallelForEachAsync[T](IEnumerable`1 source, Func`2 handleAsync, Int32 degreeOfParallelism, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Utils\Extensions\AsyncExtensions.cs:35
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_0.<<ExecuteAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:71
  at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:103
  at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:138
  at Spectre.Console.Internal.DefaultExclusivityMode.Run[T](Func`1 func) in \_\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:44
  at Spectre.Console.Progress.StartAsync[T](Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:121
  at Spectre.Console.Progress.StartAsync(Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:101
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:69
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channelIds) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:153
  at DiscordChatExporter.Cli.Commands.ExportChannelsCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportChannelsCommand.cs:19
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in \home\runner\work\CliFx\CliFx\CliFx\CliApplication.cs:191
```
Screenshots for JSON example (CLI, GUI):
![DiscordChatExporter CLI_2 31 0_ErrorMessage](https://user-images.githubusercontent.com/50897778/145678200-597b3c06-285f-4acc-8b9c-d599d97df1f2.png)
![DiscordChatExporter_2 31 0_ErrorMessage](https://user-images.githubusercontent.com/50897778/145678203-837e37d6-bc33-4191-808f-4a5883d90546.png)
This error does not happen to me with the previous version (2.30.1) of DCE.

### Steps to reproduce

For CLI version, run:
`discordchatexporter.cli.exe export --channel [channel ID] --token [login token] --output [output path] --format {HTMLLight | HTMLDark | CSV | PlainText | JSON} --after [arbitrary date or message ID] --media False`
where the []-bracketed or {}-braced options are filled in or picked.
For GUI version, pick the big (>97500-message) channel to export, click on the Download button, choose the options, then click Export.

**Comment by 96-LB** [comment]
I don't think this has to do with channel size. Looks like the error is happening when parsing an emoji reaction.

**Comment by Tyrrrz** [comment]
I think this is a bug. The error happens here:
https://github.com/Tyrrrz/DiscordChatExporter/blob/ba4ece9325c9db8cd0282be8e7d9fd108a117f43/DiscordChatExporter.Core/Discord/Data/Emoji.cs#L51

Looks like the `id` parameter is present but is null. It should be `GetStringOrNull()` there instead.

**Comment by Tyrrrz** [comment]
Ok, try the CI build
