### ISSUE TITLE
System.InvalidOperationException: Cannot read the specified JSON element as a non-empty and non-whitespace string value.

### ISSUE THREAD

**Issue by ivan** [Tyrrrz/DiscordChatExporter#765]
### Version

2.31.1

### Flavor

CLI (Command Line Interface)

### Export format

JSON

### Details

Hello,

Thank you for the very useful software. After upgrading, I reproducibly see this issue when running 2.31.1 or the CI build for 2156c6cd0ca90524bd6e52418b034334b66b5c8c on NixOS:

```
$ mkdir discord-logs && dotnet DiscordChatExporter.Cli.dll exportall -t TOKEN -f Json --parallel 8 -o discord-logs
Fetching channels...
Exporting 10216 channel(s)...
[...]
Sponsors / github_sponsors             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
projects & support / worldedit         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  13%
projects & support / worldguard        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   3%
projects & support / craftbook         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  10%
projects & support / enginehub-misc    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  20%
projects & support / api               ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%
Project Development / dev-team         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%
Project Development / git-log          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  10%


ERROR
System.InvalidOperationException: Cannot read the specified JSON element as a non-empty and non-whitespace string value.
  at JsonExtensions.Reading.StringExtensions.GetNonWhiteSpaceString(JsonElement element) in /_/JsonExtensions/Reading/StringExtensions.cs:55
  at DiscordChatExporter.Core.Discord.Data.Embeds.EmbedField.Parse(JsonElement json) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Embeds\EmbedField.cs:14
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at DiscordChatExporter.Core.Discord.Data.Embeds.Embed.Parse(JsonElement json) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Discord\Data\Embeds\Embed.cs:38
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at DiscordChatExporter.Core.Discord.Data.Message.Parse(JsonElement json)
  at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
  at System.Linq.Enumerable.ReverseIterator`1.ToArray()
  at DiscordChatExporter.Core.Discord.DiscordClient.GetMessagesAsync(Snowflake channelId, Nullable`1 after, Nullable`1 before, IProgress`1 progress, CancellationToken cancellationToken)+MoveNext()
  at DiscordChatExporter.Core.Discord.DiscordClient.GetMessagesAsync(Snowflake channelId, Nullable`1 after, Nullable`1 before, IProgress`1 progress, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:43
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:43
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:78
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_2.<<ExecuteAsync>b__2>d.MoveNext() in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:102
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.StartTaskAsync(ProgressContext progressContext, String description, Func`2 performOperationAsync) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:49
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_1.<<ExecuteAsync>b__1>d.MoveNext() in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:109
  at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_0.<<ExecuteAsync>b__0>d.MoveNext() in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:70
  at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:103
  at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:138
  at Spectre.Console.Internal.DefaultExclusivityMode.Run[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:44
  at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:121
  at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:101
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channels) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:68
  at DiscordChatExporter.Cli.Commands.ExportAllCommand.ExecuteAsync(IConsole console) in /D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportAllCommand.cs:38
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in /home/runner/work/CliFx/CliFx/CliFx/CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in /home/runner/work/CliFx/CliFx/CliFx/CliApplication.cs:191
```

You might be able to reproduce this by joining the EngineHub Discord at https://discord.com/invite/enginehub, but I have not tested this in a fresh account.

### Steps to reproduce

1. join the EngineHub Discord at https://discord.com/invite/enginehub
2. on Linux, `mkdir discord-logs && dotnet DiscordChatExporter.Cli.dll exportall -t TOKEN -f Json --parallel 8 -o discord-logs`

**Comment by ivan** [comment]
```
# dotnet DiscordChatExporter.Cli.dll --version
v2.31.1
```

(confirming that I am not running the older version where a similar-looking bug was fixed)

**Comment by Tyrrrz** [comment]
Thanks for reporting this bug. Can you please try the latest CI build?
https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/1655477909

**Comment by ivan** [comment]
Thank you very much, that seems to have fixed it.
