### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by the-jolley-boy** [Tyrrrz/DiscordChatExporter#948]
### Version

2.3

### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

Traceback (most recent call last):
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 123, in export
    return await super().build_transcript()
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\transcript.py", line 46, in build_transcript
    message_html, meta_data = await gather_messages(
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 345, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 77, in construct_message
    await self.build_message()
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 81, in build_message
    await self.build_content()
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\construct\message.py", line 120, in build_content
    self.message.content = await fill_out(self.guild, message_content, [
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\ext\html_generator.py", line 28, in fill_out
    v = await ParseMarkdown(v).standard_message_flow()
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\parse\markdown.py", line 10, in standard_message_flow
    self.https_http_links()
  File "C:\Users\kianj\AppData\Local\Programs\Python\Python39\lib\site-packages\chat_exporter\parse\markdown.py", line 274, in https_http_links
    url = re.search(pattern, word).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

### Steps to reproduce

Runs fine on my server, it is under maintenance until EOD so I can't check that version of chat exporter. Just wanted to shed light on the issue, once I gain access I can send the server version too so you can compare, but the code works fine on the server but not on my home pc.

**Comment by Tyrrrz** [comment]
Wrong project
