### ISSUE TITLE
Can't export channels with ... at the end of the name

### ISSUE THREAD

**Issue by Feathered-Serpent** [Tyrrrz/DiscordChatExporter#977]
### Version

DiscordChatExporter.Cli v2.35.0

### Flavor

CLI (Command Line Interface)

### Export format

HTML

### Details

I wanted to export all of 2022. Now at one of the servers I'm on there is a channel name with leading ... in the name. This (at least I think) causes the generation of the folder on the hard disk to fail at Windows 10 Pro 21H2

```
ERROR
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Ezatoka\Documents\Privat\Logs\Discord Exports\Science and Salad!\Unter dem Winterwind...\??zeug-kram-und-dinge (2022-01-01).html'.
  at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
  at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
  at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
  at DiscordChatExporter.Core.Exporting.MessageExporter.CreateMessageWriter(String filePath, ExportFormat format, ExportContext context) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\MessageExporter.cs:101
  at DiscordChatExporter.Core.Exporting.MessageExporter.GetWriterAsync(CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\MessageExporter.cs:56
  at DiscordChatExporter.Core.Exporting.MessageExporter.ExportMessageAsync(Message message, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\MessageExporter.cs:62
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:73
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:44
  at DiscordChatExporter.Core.Exporting.ChannelExporter.ExportChannelAsync(ExportRequest request, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Core\Exporting\ChannelExporter.cs:79
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_2.<<ExecuteAsync>b__2>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:139
  at DiscordChatExporter.Cli.Utils.Extensions.ConsoleExtensions.StartTaskAsync(ProgressContext progressContext, String description, Func`2 performOperationAsync) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Utils\Extensions\ConsoleExtensions.cs:49
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_1.<<ExecuteAsync>b__1>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:146
  at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.<>c__DisplayClass43_0.<<ExecuteAsync>b__0>d.MoveNext() in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:104
  at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:98
  at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in \_\src\Spectre.Console\Live\Progress\Progress.cs:133
  at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in \_\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:40
  at Spectre.Console.Progress.StartAsync[T](Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:116
  at Spectre.Console.Progress.StartAsync(Func`2 action) in \_\src\Spectre.Console\Live\Progress\Progress.cs:96
  at DiscordChatExporter.Cli.Commands.Base.ExportCommandBase.ExecuteAsync(IConsole console, IReadOnlyList`1 channels) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\Base\ExportCommandBase.cs:102
  at DiscordChatExporter.Cli.Commands.ExportAllCommand.ExecuteAsync(IConsole console) in D:\a\DiscordChatExporter\DiscordChatExporter\DiscordChatExporter.Cli\Commands\ExportAllCommand.cs:37
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:191
```

Is there a way I can tell the exporter to not create these dots? Or at least use Ellipsis instead which is only one unicode character?
This one -> …

### Steps to reproduce

- Create a channel on your Discord server with trailing ...
- Write something into the channel.
- Try to export this channel

**Comment by Tyrrrz** [comment]
That seems weird, the dots shouldn't cause any issues. As a workaround, can you try pre-creating the folder yourself?

**Comment by Feathered-Serpent** [comment]
I cannot, because Windows does not allow to create a folder whose name ends at one ore more dots.
If I try to create "Unter dem Winterwind..." the folder is automatically named "Unter dem Winterwind" and I cannot rename it either, as the dots are removed them as well.
I can create a folder with e.g. the name "\\?\C:\Temp..." and it will be created, but then I can't even look into it in Windows Explorer because Windows tells me, the ressource isn't available.

**Comment by Feathered-Serpent** [comment]
On other programs I use a replacement matrix if the program supports that. Like:
```
: > ∶
/ > ⁄
* > ∗
? > ？
" > ″
\ > ⧵
. > ․
| > ǀ
< > ‹
> > ›
```
Similar looking, but unicode characters, which Windows supports for file/folder names

**Comment by Tyrrrz** [comment]
I decided to keep the behavior consistent with the Windows shell and the `CreateFile()` function, which is to trim the trailing dots. Please test the CI build and see if it works.

**Comment by Feathered-Serpent** [comment]
https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/3827989580 has no artifacts to download yet, if you mean this one.

**Comment by Tyrrrz** [comment]
> [Tyrrrz/DiscordChatExporter/actions/runs/3827989580](https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/3827989580) has no artifacts to download yet, if you mean this one.

This one: https://github.com/Tyrrrz/DiscordChatExporter/actions/runs/3828045684

**Comment by Feathered-Serpent** [comment]
After installing Net 7 it works:
![Clipboard01](https://user-images.githubusercontent.com/72162369/210458689-dcd66899-fa77-4f84-a302-45e7f9324686.png)
